openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://api.keypeer.org
info:
  description: Proposed API
  version: "1.0"
  title: Keypeer Api
  contact:
    email: admin@keypeer.org
  license:
    name: GPLv2
    url: 'https://api.keypeer.org/v10'
tags:
  - name: admins
    description: Secured Admin-only calls
  - name: consumers
    description: Operations available on consumers
  - name: providers
    description: Operations available on providers
  - name: applications
    description: Operations available on applications
paths:
  /v10/providers:
    get:
      tags:
        - providers
      summary: Provider ID list
      description: Returns a list of providers
      responses:
        '200':
          description: Returns a list of providers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/provider'
        '400':
          description: bad input parameter
  /v10/providers/{name}:
    post:
      tags:
        - admins
      summary: Add provider
      description: |
        Returns new provider ID (and?) if provider is added
      parameters:
        - in: path
          name: name
          description: Name of the provider to create
          required: true
          schema:
            type: string
      requestBody:
        description: Request to add consumer application 
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/provider'
      responses:
        '200':
          description: Return New Provider name/key
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/provider'
        '400':
          description: bad input parameter
  /v10/providers/{provider_id}:
    get:
      tags:
        - providers
      summary: Service API KEY
      description: |
        Returns the provider service api key for {provider_id} 
      parameters:
        - in: path
          name: provider_id
          description: Internal ID for available services
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Return service api key
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/provider'
        '400':
          description: bad input parameter
  /v10/consumers/{consumer_id}:
    get:
      tags:
        - consumers
      summary: Request user data
      description: |
        Returns a dict containing varoius user data
      parameters:
        - in: path
          name: consumer_id
          description: End User ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Return User Data
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/consumer'
        '400':
          description: bad input parameter
  /v10/consumers:
    get:
      tags:
        - admins
      summary: Request user data
      description: |
        Returns a dict userids
      responses:
        '200':
          description: Return Userids
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/consumer'
        '400':
          description: bad input parameter
  /v10/consumers/{consumer_id}/applications/{application_id}:
    get:
      tags:
        - consumers
      summary: Retrieve Service Api keys for users application, application_id
      description: |
        Returns service api key
      parameters:
        - in: path
          name: consumer_id
          description: Consumer ID
          required: true
          schema:
            type: string
        - in: path
          name: application_id
          description: Consumer Application ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Returns service api keys for Application and user
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/consumer_application'
        '400':
          description: bad input parameter
    post:
      tags:
        - consumers
        - admins
      summary: Add consumer application
      description: |
        Returns true if consumer application is added
      parameters:
        - in: path
          name: consumer_id
          description: consumer_id
          required: true
          schema:
            type: string
        - in: path
          name: application_id
          description: Consumer Application ID
          required: true
          schema:
            type: string
      requestBody:
        description: Request to add consumer application 
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/consumer'
      responses:
        '201':
          description: success
    delete:
      tags:
        - consumers
        - admins
      summary: remove consumer application
      description: |
        Returns true if consumer application is updated
      parameters:
        - in: path
          name: consumer_id
          description: Consumer ID
          required: true
          schema:
            type: string
        - in: path
          name: application_id
          description: Consumer Application ID
          required: true
          schema:
            type: string
      responses:
        '201':
          description: delete success
  /v10/consumers/{consumer_id}/providers/{provider_id}:
    get:
      tags:
        - consumers
      summary: Retrieve Service Api keys for users provider, provider_id
      description: |
        Returns service api key
      parameters:
        - in: path
          name: consumer_id
          description: Consumer ID
          required: true
          schema:
            type: string
        - in: path
          name: provider_id
          description: Consumer Provider ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Returns service api keys for Provider and user
          content:
            provider/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/consumer_provider'
        '400':
          description: bad input parameter
    post:
      tags:
        - consumers
        - admins
      summary: Add consumer provider
      description: |
        Returns true if consumer provider is added
      parameters:
        - in: path
          name: consumer_id
          description: consumer_id
          required: true
          schema:
            type: string
        - in: path
          name: provider_id
          description: Consumer Provider ID
          required: true
          schema:
            type: string
      requestBody:
        description: Request to add consumer provider 
        required: true
        content:
          provider/json:
            schema:
              $ref: '#/components/schemas/consumer'
      responses:
        '201':
          description: success
    delete:
      tags:
        - consumers
        - admins
      summary: remove consumer provider
      description: |
        Returns true if consumer provider is updated
      parameters:
        - in: path
          name: consumer_id
          description: Consumer ID
          required: true
          schema:
            type: string
        - in: path
          name: provider_id
          description: Consumer Provider ID
          required: true
          schema:
            type: string
      responses:
        '201':
          description: delete success

  /v10/applications:
    get:
      tags:
        - admins
      summary: Return array of applications
      description: |
         Obtain list of application providers
      responses:
        '200':
          description: Returns service api key
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/application'
        '400':
          description: bad input parameter
    post:
      tags:
        - admins
      summary: Add application application
      description: |
        Returns true if consumer application is added
      requestBody:
        description: Request to add consumer application 
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/application'
      responses:
        '201':
          description: success
  /v10/applications/{application_id}:
    get:
      tags:
        - consumers
        - admins
      summary: Return array of providers for an application
      description: |
         Obtain list of application providers
      parameters:
        - in: path
          name: application_id
          description: Consumer Application ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Returns service api key
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/application'
        '400':
          description: bad input parameter
  /v10/applications/{application_id}/providers:
    get:
      tags:
        - consumers
      summary: Return array of application providers
      description: |
         Obtain application provider keys
      parameters:
        - in: path
          name: application_id
          description: Consumer Application ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Return array of application provider keys
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/application'
        '400':
          description: bad input parameter
  /v10/applications/{application_id}/providers/{provider_id}:
    get:
      tags:
        - consumers
      summary: Return provider keys for application & provider
      description: |
         Obtain application provider keys
      parameters:
        - in: path
          name: application_id
          description: Consumer Application ID
          required: true
          schema:
            type: string
        - in: path
          name: provider_id
          description: Internal ID for available services
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Return array of application provider keys
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/application'
        '400':
          description: bad input parameter
components:
  schemas:
    provider:
      type: object
      properties:
        provider_id:
          type: integer
        uuid:
          type: string
          format: uuid
        name:
          type: string
        uri:
          type: string
          format: url
      example:
      - provider_id: 1
        uuid: d290f1ee-6c54-4b01-90e6-d701748f0851
        name: Mapbox
        uri: https://mapbox.com
      - provider_id: 2
        uuid: d290f1ee-6c54-4b01-90e6-78987hj23678
        name: Here
        uri: https://here.com
    consumer:
      type: array
      items:
        type: object
        properties:
          consumer_id:
            type: integer
          uuid:
            type: string
            format: uuid
        example:
        - consumer_id: 1
          uuid: d290f1ff-6c54-4b01-90e6-d701748f0851
        - consumer_id: 2
          uuid: d290f1ff-6c54-4b01-90e6-78987hj23678
    consumer_application:
      type: array
      items:
        type: object
        properties:
          consumer_id:
            type: integer
          application_id:
            type: integer
          provider_id:
            type: integer
          expiry:
            type: string
            description: ISO 8601 Format
        example:
        - application_id: d290f1ee-6c54-4b01-90e6-hjsd6777h389
          provider_id: d290f1ee-6c54-4b01-90e6-78987hj23678
          expiry: 2023-03-25T16:33:23Z
        - application_id: d290f1ee-6c54-4b01-90e6-hjsd6777h389
          provider_id: d290f1ee-6c54-4b01-90e6-78987hj23678
          expiry: 2023-03-25T16:33:23Z
    consumer_provider:
      type: array
      items:
          type: object
          properties:
            provider_id:
              type: string
              format: uuid
            service_api_key:
              type: string
              format: uuid
          example:
          - provider_id: d290f1ee-6c54-4b01-90e6-78987hj23678
            service_api_key: d290f1ee-6c54-4b01-90e6-78987hj23678
          - provider_id: d290f1ee-6c54-4b01-90e6-78987hj23678
            service_api_key: d290f1ee-6c54-4b01-90e6-78987hj23678
    application:
      type: array
      items:
        type: object
        properties:  
          application_id:
            type: integer
          uuid:
            type: string
            format: uuid
          name:
            type: string
          uri:
            type: string
            format: url
        example:
        - application_id: 1
          uuid: d290f1ee-6c54-4b01-90e6-d701748f0851
          name: Puremaps
          uri: https://puremaps.org

